# -*- coding: utf-8 -*-
"""wykl1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1XQ0MZYQsN6D1ZYcbovHkOUzJmXWuqV0M
"""

#from numpy import random
import numpy as np
# utwórz tablicę zawierającą 10 zer,
x = np.zeros(10)
print(x)
# utwórz tablicę zawierającą 10 piątek,
y = array([5,5,5,5,5,5,5,5,5,5])
print(y)
# utwórz tablicę zawierającą liczby od 10 do 50,
z = arange(10, 51, 1)
print(z)
# utwórz macierz (tablica wielowymiarowa) o wymiarach 3x3 zawierającą liczby od 0 do 8,
m = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]]);
print(m) 
# utwórz macierz jednostkową o wymiarach 3x3,
p = np.eye(3)
print(p)
# utwórz macierz o wymiarach 5x5 zawierającą liczby z dystrybucji normalnej (Gaussa),
o = random.normal(0, 0.5, (5,5))
print (o)
# # utwórz macierz o wymiarach 10x10 zawierającą liczby od 0,01 do 1 z krokiem 0,01,
i = np.linspace(0.01, 1.0, 100).reshape(10, 10)
print (i)
# # utwórz tablicę zawierającą 20 liniowo rozłożonych liczb między 0 a 1 (włącznie z 0 i 1),
u =  np.linspace(0, 1, 20)
print (u)
# # utwórz tablicę zawierającą losowe liczby z przedziału (1, 25), następnie zamień
# # ją na macierz o wymiarach 5 x 5 z tymi samymi liczbami:
a_random = np.random.randint(2, 25, 25).reshape(5, 5)
print(a_random)
# # oblicz sumę wszystkich liczb w ww. macierzy,
t1 = a_random.sum()
print(t1)
# # oblicz średnią wszystkich liczb w ww. macierzy,
t2= a_random.mean()
print(t2)
# # oblicz standardową dewiację dla liczb w ww. macierzy,
t3 = np.std(a_random)
print(t3)
# # oblicz sumę każdej kolumny ww. macierzy i zapisz ją do tablicy.
t4 = a_random.sum(axis=0)
print(t4)
# # utwórz macierz o wymiarach 5x5 zawierającą losowe liczby z przedziału (0, 100) i:
r = np.random.randint(1, 100, (5, 5))
print(r)
# # oblicz medianę tych liczb,
r1 = np.median(r)
print(r1)
# # znajdź najmniejszą liczbę tej macierzy,
r2 =  r.min()
print(r2)
# # znajdź największą liczbę tej macierzy.
r3 = r.max()
print(r3)
# # utwórz macierz o wymiarach różnych od siebie i większych od 1, zawierającą losowe liczby z przedziału (0, 100) i dokonaj jej transpozycji,
e = np.random.randint(1, 100, (4, 3))
print(e.T)
# # utwórz dwie macierze o odpowiednich wymiarach (doczytać), większych od 2 i dodaj je do siebie,
mx = np.random.random((4, 4))
print(mx)
my = np.random.random((4, 3))
print(my)
my = np.append(my, np.zeros((4, 1)), axis=1)
print(my)
# # utwórz dwie macierze o odpowiednich wymiarach (doczytać) różnych od siebie i większych od 2, a następnie pomnóż je przez siebie za pomocą dwóch różnych funkcji (np. ‘matmul’ i ‘multiply’),
mxd = np.random.random((3, 4))
myd = np.random.random((4, 3))
print(np.multiply(mxd.T, myd))
print(np.matmul(mxd, myd))