# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xdkJiUidwPfHwJgK1n7eNHxRICmM0f06
"""

import numpy as np
import pandas as pd
#Wczytanie pliku "samochody1tys.csv"
df = pd.read_csv('samochody1tys.csv')
#skopwiowanie wartosci do innej zmiennej
dataCopy = df.copy()
print(dataCopy)
#sortowanie według konkretnej kolumny
dataCopy1= dataCopy.sort_index(axis=1, ascending=False)
print(dataCopy1)
#sortowanie po przebiegu
dataCopy2= dataCopy.sort_values(by='przebieg')
print(dataCopy2)
#grupowanie po kilku kolumnach
dataCopy3= dataCopy.groupby(["marka","model"]).sum()
print(dataCopy3)
#grupowanie po konkretnej wartości
dataCopy4= dataCopy.groupby("marka").sum()
print(dataCopy4)
#wybranie 15 samochodów z największym id
dataCopy5 = dataCopy.nlargest(15, 'id')
print(dataCopy5)
# wybranie 50 rekordów i usunięcie duplikatów w kolumnie marka
dataCopy6 = dataCopy.sample(50).drop_duplicates('wojewodztwo')
print(dataCopy6)
#wybranie pojedyńczej kolumny 
dataCopy7 = dataCopy['model'] 
print(dataCopy7)
#pobieranie konkretnych kolumn z przedziału id
dataCopy8 = dataCopy.loc[100:130,['wojewodztwo','marka']]
print(dataCopy8)
#zliczenie unikalnych rekordów w każdej z kolumn
dataCopy9 = dataCopy.nunique()
print(dataCopy9)