# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QK_CPQKnqLQaHIs2gKjjDEKxW7igd1Rb
"""

#otwarcie pliku
file = open('Izdebska.txt')



# #otwarcie pliku tylko do odczytu
file = open('Izdebska.txt', 'r')
# #otwarcie pliku do nadpisania
file = open('Izdebska.txt','w')
#typ pliku
type(file)
#otwarcie pliku binarnego tylko do odczytu
file = open('Izdebska.txt', 'rb')
#otwarcie pliku binarnego do nadpisania
file = open('Izdebska.txt','wb')
#otworzenie pliku w formie surowej
file = open('Izdebska.txt', 'rb',buffering=0)
type(file)
#czytanie pliku oraz jego wyświetlenie
with open('Izdebska.txt', 'r') as reader:
 print(reader.read())
#wyświetlenie konkretnej wartości bajtów każdej linii
with open('Izdebska.txt', 'r') as reader:
 print(reader.read(8))
 print(reader.read(8))
 print(reader.read(8))
 print(reader.read(8))
#wyświetlenie pliku w formie listy
file.readlines()  
#Iterowanie po każdej linii w pliku
with open('Izdebska.txt', 'r') as reader:
 line = reader.readline()
 while line != '':  # The EOF char is an empty string
  print(line, end='')
  line = reader.readline()
# #Uproszczenie powyższego przykładu 
with open('Izdebska.txt', 'r') as reader:
 for line in reader:
  print(line, end='')
#Pisanie plików
with open('Izdebska.txt', 'r') as reader:
    # Note: readlines doesn't trim the line endings
    Izdebska = reader.readlines()

with open('Izdebska_reversed.txt', 'w') as writer:
    # Alternatively you could use
    # writer.writelines(reversed(Izdebska))

    # Write the Izdebska to the file in reversed order
    for breed in reversed(Izdebska):
        writer.write(breed)
#Pracowanie z bajtami
with open('Izdebska.txt', 'rb') as reader :
  print(reader.readline())
#Wyświetlenie kilku bitów pliku png
with open('Izdebska.png', 'rb') as byte_reader:
 print(byte_reader.read(1))
 print(byte_reader.read(3))
 print(byte_reader.read(2))
 print(byte_reader.read(1))
 #Praca z dwoma plikami na raz
d_path = 'Izdebska.txt'
d_r_path = 'Izdebska_reversed.txt'
with open(d_path, 'r') as reader, open(d_r_path, 'w') as writer:
    dog_breeds = reader.readlines()
    writer.writelines(reversed(dog_breeds))
#Dołączanie do pliku 
with open('Izdebska.txt', 'a') as a_writer:
    a_writer.write('\nMERRY CHRISTMAS')
with open('Izdebska.txt', 'r') as reader:
 print(reader.read())

#Tworzenie własnego menedżera kontekstu
class my_file_reader():
    def __init__(self, file_path):
        self.__path = file_path
        self.__file_object = None

    def __enter__(self):
        self.__file_object = open(self.__path)
        return self

    def __exit__(self, type, val, tb):
        self.__file_object.close()